# Generated by Django 3.1.2 on 2020-12-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipediaPost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/posts/%Y/%m/%d/slug'),
        ),
    ]
