# Generated by Django 3.1.2 on 2020-12-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipediaPost', '0002_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
