# Generated by Django 3.1.2 on 2020-12-12 22:17

import RecipediaPost.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipediaPost', '0004_auto_20201211_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to=RecipediaPost.models.add_slug),
        ),
    ]
