# Generated by Django 3.1.2 on 2020-12-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipediaPost', '0006_auto_20201213_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
